### ISSUE TITLE
Cannot see Greenkeeper logo

### ISSUE THREAD

**Issue by NotMoni** [octokit/request-action#11]
![Screen Shot 2020-05-01 at 5 10 32 PM](https://user-images.githubusercontent.com/40552237/80842090-bab26a00-8bce-11ea-953e-51227b3ac857.png)

**Comment by gr2m** [comment]
Thanks for letting me know about the problem! Turns out that Greenkeeper was not properly installed on the repository. I fixed that now, so the badge should appear soon

**Comment by NotMoni** [comment]
Nice hope I can help 🦄
