### ISSUE TITLE
`POST /repos/{owner}/{repo}/deployments`: cannot set `required_contexts` parameter

### ISSUE THREAD

**Issue by y-nk** [octokit/request-action#120]
![image](https://user-images.githubusercontent.com/411625/132341064-5b0ebe71-4a10-4238-b6e0-ec63b81d142e.png)

I tried:

- `required_contexts: ""` → yaml does not complain but API does 
- `required_contexts: false` → yaml does not complain but API does
- `required_contexts: []`  → github action does not start, claims some syntax error in the yaml
- `required_contexts: null` → github action does start despite the error, but sends `undefined` instead of `null` which ends in error (as shown)

The docs of the endpoint:
![image](https://user-images.githubusercontent.com/411625/132341289-f40c9ac3-3ed3-4771-b263-a8dc34852bfc.png)

Could you have a look ?

( Already filed an issue here: https://github.com/SchemaStore/schemastore/issues/1819 )

**Comment by gr2m** [comment]
Can you try

```yml
required_contexts: |
  []
```

**Comment by y-nk** [comment]
@gr2m It went similarly. The issue being in schema store if i ever want to pass something else than declared.

**Comment by gr2m** [comment]
what exact error did you get? Can you enable debugging as described in https://github.com/octokit/request-action#debugging and share the full logs?

**Comment by y-nk** [comment]
i've moved away from it at the moment, so i cannot produce log anymore. that said, the log was pretty clear, the schema was invalid since an array was provided, as you could experience from vscode .

**Comment by y-nk** [comment]
thank you @sarkis
