### ISSUE TITLE
Github Action Unexpected input(s) Warning

### ISSUE THREAD

**Issue by drey0143143** [octokit/request-action#131]
I'm getting this warning after my workflow complete running.How can I fix this please? by the way,I am running Github Action with terragrunt

```
Unexpected input(s) 'tf_action_version', valid inputs are ['entryPoint', 'args', 'tf_actions_subcommand', 'tf_actions_binary', 'tf_actions_version', 'tg_actions_version', 'tf_actions_cli_credentials_hostname', 'tf_actions_cli_credentials_token', 'tf_actions_comment', 'tf_actions_working_dir', 'tf_actions_fmt_write']

```

**Comment by rcdailey** [comment]
I'm not convinced this is a support request. It feels like a bug. This warning gets generated when using the example YAML from the readme.

**Comment by gr2m** [comment]
closing in favor of https://github.com/octokit/request-action/issues/26
