### ISSUE TITLE
[ASK]: What is GITHUB_TOKEN??

### ISSUE THREAD

**Issue by chanjungkim** [octokit/request-action#238]
### What happened?

I get this error:

Error: .github/workflows/android-ci.yml (Line: 37, Col: 24):
Error: The template is not valid. .github/workflows/android-ci.yml (Line: 37, Col: [2](https://github.com/Flutter-Study-Collection/flutter-study/actions/runs/4593032261/jobs/8110592882#step:5:2)4): Error reading JToken from JsonReader. Path '', line 0, position 0.

I think this is because I didn't add GITHUB_TOKEN. Where can I get this token?

### Versions

v2.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi @chanjungkim! You can find documentation about how to [generate](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) a GitHub Personal Access Token. Once you've generated a token with the proper permissions, you can add it as a GitHub Actions secret and pass it into your workflow.
