### ISSUE TITLE
Having this problem "Bad Credentials"

### ISSUE THREAD

**Issue by saminBee** [octokit/request-action#252]
### What happened?

```
Warning: Unexpected input(s) 'owner', 'repo', valid inputs are ['route', 'mediaType']
Run octokit/request-action@v[2](https://github.com/***/***/actions/runs/5168372820/jobs/9309914439#step:2:2).x
  with:
    route: GET /repos/{owner}/{repo}/releases/latest
    owner: ***
    repo: ***
    mediaType: {}
  env:
    GITHUB_TOKEN: ***
GET /repos/{owner}/{repo}/releases/latest
> owner: ****
> repo: ******
> mediaType: [object Object]
< [4](https://github.com/***/***/actions/runs/5168372820/jobs/9309914439#step:2:4)01 21[9](https://github.com/***/***/actions/runs/5168372820/jobs/9309914439#step:2:9)ms
Error: Bad credentials
```

### Versions

octokit/request-action@v2.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
Can you share your workflow file?

**Comment by saminBee** [comment]
on:
  workflow_dispatch:
    inputs:
      mail:
        description: 'Customer Email'
        required: true

name: "Hishabee E-commerce"
jobs:
  build:
    name: Hishabee E-commerce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run flutter_launcher_icons
      - run: flutter build apk
      - run: flutter build appbundle --release


      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v3.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      - name: Push to Releases aab
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*"
          tag: v2.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: Hishabee
          repo: hishabee_ecommerce
        env:
          GITHUB_TOKEN: ******
      - run: echo "${{ fromJson(steps.get_latest_release.outputs.data)['assets'][0]['browser_download_url'] }}"

There are also other actions, i hope this is enough to sort the problem @gr2m

**Comment by saminBee** [comment]
any update? @gr2m

**Comment by gr2m** [comment]
> ```yaml
>       - name: Push to Releases aab
>         uses: ncipollo/release-action@v1
>         with:
>           artifacts: "build/app/outputs/bundle/release/*"
>           tag: v2.0.${{ github.run_number }}
>           token: ${{ secrets.TOKEN }}
> ```

Here you set token to `secrets.TOKEN`

> ```yaml
>       - uses: octokit/request-action@v2.x
>         id: get_latest_release
>         with:
>           route: GET /repos/{owner}/{repo}/releases/latest
>           owner: Hishabee
>           repo: hishabee_ecommerce
>         env:
>           GITHUB_TOKEN: ******
> ```

What are you doing here?

Two more questions

1. What type of token is `SECRETS.token`?
2. Is this workflow running in the `Hishabee/hishabee_ecommerce` repository?

**Comment by saminBee** [comment]
1. this token is a GitHub secret token. I am pushing the built aab file into the release bucket list of the repository. 
2. Yes, this workflow is running in HishaBee/hishabee_ecommerce. 

I have been running these github actions for about 6+ months, and it was working fine. This action basically helps our customer to get their own ecommerce mobile app by providing their email, we provided 200+ website running this action. But suddenly the action octokit showing 401 error

**Comment by saminBee** [comment]
- uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: Hishabee
          repo: hishabee_ecommerce
        env:
          GITHUB_TOKEN: ******
in here i am accesing the downloadable url which we will provide to our customer through email

**Comment by saminBee** [comment]
Thank you so much. Problem solved. I forgot that i have changed my github token for logging in in my new laptops android studio. That is why it was showing Bad Credentials.
