### ISSUE TITLE
> I see some repositories using `npm run build`

### ISSUE THREAD

**Issue by najmulsheik** [octokit/request-action#259]
> I see some repositories using `npm run build`

I'd always run it with `npm run build --if-present`, just like the others. This makes sure that we verify that the dependencies only used for building are tested as part of the CI

> * `npm run validate:ts`
> * `npm run test:typescript`
> * `npm run test:ts`

I'm tending towards `test:tsc` to be as clear as possible. In other project I use `test:tsd` for type-only tests using [`tsd`](https://github.com/SamVerschueren/tsd#readme), and in future when I hope me move away from TS source code I could imagine @octokit to use that, too ([Example](https://github.com/gr2m/github-project/blob/2cc6d4eb6ea2001cf7faa0717bb1e915debefc74/package.json#L11-L12))

But I'm open to anything, it's not set in stone. I do agree we should normalize it across the @octokit repositories though

_Originally posted by @gr2m in https://github.com/octokit/.github/issues/13#issuecomment-1200523926_

**Comment by kfcampbell** [comment]
This seems off-topic/potentially spam, closing for that reason.
