### ISSUE TITLE
[BUG]: Available inputs not correctly listed in action.yml

### ISSUE THREAD

**Issue by jackoat29** [octokit/request-action#309]
### What happened?

Not sure if this fits as a bug or documentation.

When using this GitHub Action within VS Code with the GitHub Actions extension; the syntax highlighting / linting is broken. See:
![image](https://github.com/octokit/request-action/assets/169434380/dbe60fb5-f0ea-4208-adc4-cdd16abe6aad)
and
![image](https://github.com/octokit/request-action/assets/169434380/96c51c3a-ffa8-414f-abd4-51738f31f68c)

I believe the reason for that is because in the [`action.yml`](https://github.com/octokit/request-action/blob/main/action.yml) file, only 2 inputs are defined, and the others are not. See [after line 6](https://github.com/octokit/request-action/blob/1f5f8ff67cfd43e6d1abe41548675d93e4f402c5/action.yml#L6).

The solution to this should be as simple as adding name and description for the other inputs as well. As in [this file from another GitHub Action](https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/action.yml#L5).

### Versions

v2.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
This is a known issue for a long time, unfortunately there is nothing we can do about it. Closing in favor of #26
